name: Python Linting
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
      - name: Lint exodus.py
        run: |
          flake8 --ignore E501,W503 packages/seacas/scripts/exodus3.in.py
      - name: Lint exomerge.py
        if: success() || failure()
        run: |
          flake8 --ignore E501,W503,W504 packages/seacas/scripts/exomerge3.py
      - name: Lint exodus tests
        if: success() || failure()
        run: |
          flake8 --ignore E501,E402,W503,W605 packages/seacas/scripts/tests
